# Foundation application configuration
app-name = "secure-notes"
friendly-app-name = "Secure Notes"
launcher-app-name = "Notes"
description = "Store and search private notes"
icon = "resources/icon.svg"
app-id = "0x536563757265204e6f746573204d5650"
version = "0.1.0"
min-keyos-version = "1.0.0"
signing-identity = "Owen Foundation Trial"

[publisher]
name = "Owen / Foundation trial"
contact-email = "hello@example.com"
support-url = "https://foundation.xyz/support"

[permissions]
template = ["gui-app", "fs-generic"]
"os/settings" = ["GetDeviceName", "GetLocale", "GetPrimeColor"]
