appId = "0x536563757265204e6f746573204d5650"

[appName]
en = "Secure Notes"

[permissions]
"os/fs" = [
    "AtomicCopy",
    "CloseDir",
    "CloseFile",
    "CreateDirMessage",
    "Flush",
    "FlushFs",
    "GetMetadata",
    "GetAirlockReadAccess",
    "GetSystemAppDataReadAccess",
    "GetSystemAppDataWriteAccess",
    "GetUsbReadAccess",
    "GetUserReadAccess",
    "MapFileMessage",
    "NextEntry",
    "OpenDirMessage",
    "OpenFileMessage",
    "ReadFile",
    "Remove",
    "Rename",
    "SeekFile",
    "SetLen",
    "TruncateFile",
    "WriteFile",
]
"os/gui-server" = [
    "AnimateNextFrame",
    "HideKeyboard",
    "RegisterAppMessage",
    "RequestRedraw",
    "ShowModal",
    "SubmitFrame",
    "UpdateKeyboard",
]
"os/settings" = [
    "GetDebugTouch",
    "GetDeviceName",
    "GetLocale",
    "GetPrimeColor",
    "GetSystemTheme",
    "SubscribeDebugTouch",
    "SubscribeSystemTheme",
]
