[fs-generic]
"os/fs" = [
    "OpenDirMessage",
    "OpenFileMessage",
    "CloseFile",
    "CloseDir",
    "CreateDirMessage",
    "ReadFile",
    "SeekFile",
    "WriteFile",
    "TruncateFile",
    "SetLen",
    "GetMetadata",
    "GetAirlockReadAccess",
    "NextEntry",
    "GetUsbReadAccess",
    "GetUserReadAccess",
    "Flush",
    "FlushFs",
    "Remove",
    "Rename",
    "AtomicCopy",
    "AsyncRead",
    "AsyncWrite",
    "AsyncCopyBlock",
    "SubscribeFilesystemEvent",
    "GetSystemAppDataReadAccess",
    "GetSystemAppDataWriteAccess",
]
[gui-app]
"os/fs" = [
    "OpenDirMessage",
    "CloseDir",
    "NextEntry",
    "MapFileMessage",
    "GetMetadata",
]
"os/gui-server" = [
    "RegisterAppMessage",
    "RequestRedraw",
    "AnimateNextFrame",
    "SubmitFrame",
    "UpdateKeyboard",
    "HideKeyboard",
    "ShowModal",
]
"os/settings" = [
    "GetSystemTheme",
    "SubscribeSystemTheme",
    "GetDebugTouch",
    "SubscribeDebugTouch",
]
[navigable]
"os/gui-server" = [
    "GetPendingNavRequest",
    "FinishResponse",
    "NavigationCancel",
]
